//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovik
{
    using System;
    using System.Collections.Generic;
    
    public partial class SostavOperation
    {
        public int IdSostavOperation { get; set; }
        public int IdOperation { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> ValueMan { get; set; }
        public Nullable<double> ItogPrice { get; set; }
    
        public virtual Operation Operation { get; set; }
    }
}
